/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7n6TWEtca3W
 */


export function Featured() {
  return (
    <section className="w-full py-12">
      <div className="container grid items-start gap-6 px-4 md:gap-8 lg:grid-cols-2 xl:grid-cols-4 xl:gap-10">
        
        <div className="flex flex-col gap-2">
          <img
            alt="Product image"
            className="aspect-square rounded-lg object-cover"
            height="300"
            src="/placeholder.svg"
            width="300"
          />
          <div className="flex flex-col gap-1.5">
            <h3 className="font-semibold text-lg">Vintage Leather Messenger Bag</h3>
            <p className="font-semibold">$79.99</p>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <img
            alt="Product image"
            className="aspect-square rounded-lg object-cover"
            height="300"
            src="/placeholder.svg"
            width="300"
          />
          <div className="flex flex-col gap-1.5">
            <h3 className="font-semibold text-lg">Classic Aviator Sunglasses</h3>
            <p className="font-semibold">$49.99</p>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <img
            alt="Product image"
            className="aspect-square rounded-lg object-cover"
            height="300"
            src="/placeholder.svg"
            width="300"
          />
          <div className="flex flex-col gap-1.5">
            <h3 className="font-semibold text-lg">Retro Bluetooth Speaker</h3>
            <p className="font-semibold">$29.99</p>
          </div>
        </div>
        <div className="flex flex-col gap-2">
          <img
            alt="Product image"
            className="aspect-square rounded-lg object-cover"
            height="300"
            src="/placeholder.svg"
            width="300"
          />
          <div className="flex flex-col gap-1.5">
            <h3 className="font-semibold text-lg">Wireless Earbuds Pro</h3>
            <p className="font-semibold">$99.99</p>
          </div>
        </div>
      </div>
    </section>
  )
}
